// Generated by CoffeeScript 1.3.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

define(['view'], function(View) {
  var ItemView;
  ItemView = (function(_super) {

    __extends(ItemView, _super);

    ItemView.name = 'ItemView';

    function ItemView() {
      return ItemView.__super__.constructor.apply(this, arguments);
    }

    ItemView.prototype.template = null;

    ItemView.prototype.render = function() {
      return this.$el.html(this.template(this.model.toJSON()));
    };

    ItemView.prototype.dispose = function() {
      return this.remove();
    };

    return ItemView;

  })(View);
  return ItemView;
});
